name: test

on: [ push, pull_request ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test AutoTag.Core.Test --no-build --verbosity normal
  
  integration-tests:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test AutoTag.CLI.Test --no-build --verbosity normal